export const countriesObsolete = [
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo, The Democratic Republic of the',
  'Cook Islands',
  'Costa Rica',
  'Cote D\'Ivoire',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and Mcdonald Islands',
  'Holy See (Vatican City State)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran, Islamic Republic Of',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, Democratic People\'S Republic of',
  'Korea, Republic of',
  'Kuwait',
  'Kyrgyzstan',
  'Lao People\'S Democratic Republic',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libyan Arab Jamahiriya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia, The Former Yugoslav Republic of',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia, Federated States of',
  'Moldova, Republic of',
  'Monaco',
  'Mongolia',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestinian Territory, Occupied',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'RWANDA',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia and Montenegro',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan, Province of China',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Viet Nam',
  'Virgin Islands, British',
  'Virgin Islands, U.S.',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
]

export const languagesObsolete = [
  'Afar',
  'Abkhazian',
  'Avestan',
  'Afrikaans',
  'Akan',
  'Amharic',
  'Aragonese',
  'Arabic',
  'Assamese',
  'Avaric',
  'Aymara',
  'Azerbaijani',
  'Bashkir',
  'Belarusian',
  'Bulgarian',
  'Bihari languages',
  'Bislama',
  'Bambara',
  'Bengali',
  'Tibetan',
  'Breton',
  'Bosnian',
  'Catalan; Valencian',
  'Chechen',
  'Chamorro',
  'Corsican',
  'Cree',
  'Czech',
  'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic',
  'Chuvash',
  'Welsh',
  'Danish',
  'German',
  'Divehi; Dhivehi; Maldivian',
  'Dzongkha',
  'Ewe',
  'Greek, Modern (1453-)',
  'English',
  'Esperanto',
  'Spanish; Castilian',
  'Estonian',
  'Basque',
  'Persian',
  'Fulah',
  'Finnish',
  'Fijian',
  'Faroese',
  'French',
  'Western Frisian',
  'Irish',
  'Gaelic; Scomttish Gaelic',
  'Galician',
  'Guarani',
  'Gujarati',
  'Manx',
  'Hausa',
  'Hebrew',
  'Hindi',
  'Hiri Motu',
  'Croatian',
  'Haitian; Haitian Creole',
  'Hungarian',
  'Armenian',
  'Herero',
  'Interlingua (International Auxiliary Language Association)',
  'Indonesian',
  'Interlingue; Occidental',
  'Igbo',
  'Sichuan Yi; Nuosu',
  'Inupiaq',
  'Ido',
  'Icelandic',
  'Italian',
  'Inuktitut',
  'Japanese',
  'Javanese',
  'Georgian',
  'Kongo',
  'Kikuyu; Gikuyu',
  'Kuanyama; Kwanyama',
  'Kazakh',
  'Kalaallisut; Greenlandic',
  'Central Khmer',
  'Kannada',
  'Korean',
  'Kanuri',
  'Kashmiri',
  'Kurdish',
  'Komi',
  'Cornish',
  'Kirghiz; Kyrgyz',
  'Latin',
  'Luxembourgish; Letzeburgesch',
  'Ganda',
  'Limburgan; Limburger; Limburgish',
  'Lingala',
  'Lao',
  'Lithuanian',
  'Luba-Katanga',
  'Latvian',
  'Malagasy',
  'Marshallese',
  'Maori',
  'Macedonian',
  'Malayalam',
  'Mongolian',
  'Marathi',
  'Malay',
  'Maltese',
  'Burmese',
  'Nauru',
  'Bokmål, Norwegian; Norwegian Bokmål',
  'Ndebele, North; North Ndebele',
  'Nepali',
  'Ndonga',
  'Dutch; Flemish',
  'Norwegian Nynorsk; Nynorsk, Norwegian',
  'Norwegian',
  'Ndebele, South; South Ndebele',
  'Navajo; Navaho',
  'Chichewa; Chewa; Nyanja',
  'Occitan (post 1500)',
  'Ojibwa',
  'Oromo',
  'Oriya',
  'Ossetian; Ossetic',
  'Panjabi; Punjabi',
  'Pali',
  'Polish',
  'Pushto; Pashto',
  'Portuguese',
  'Quechua',
  'Romansh',
  'Rundi',
  'Romanian; Moldavian; Moldovan',
  'Russian',
  'Kinyarwanda',
  'Sanskrit',
  'Sardinian',
  'Sindhi',
  'Northern Sami',
  'Sango',
  'Sinhala; Sinhalese',
  'Slovak',
  'Slovenian',
  'Samoan',
  'Shona',
  'Somali',
  'Albanian',
  'Serbian',
  'Swati',
  'Sotho, Southern',
  'Sundanese',
  'Swedish',
  'Swahili',
  'Tamil',
  'Telugu',
  'Tajik',
  'Thai',
  'Tigrinya',
  'Turkmen',
  'Tagalog',
  'Tswana',
  'Tonga (Tonga Islands)',
  'Turkish',
  'Tsonga',
  'Tatar',
  'Twi',
  'Tahitian',
  'Uighur; Uyghur',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Venda',
  'Vietnamese',
  'Volapük',
  'Walloon',
  'Wolof',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Zhuang; Chuang',
  'Chinese',
  'Zulu'
]

export const nationalitiesObsolete = [
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Andorran',
  'Angolan',
  'Antiguans',
  'Argentinean',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bahamian',
  'Bahraini',
  'Bangladeshi',
  'Barbadian',
  'Barbudans',
  'Batswana',
  'Belarusian',
  'Belgian',
  'Belizean',
  'Beninese',
  'Bhutanese',
  'Bolivian',
  'Bosnian',
  'Brazilian',
  'British',
  'Bruneian',
  'Bulgarian',
  'Burkinabe',
  'Burmese',
  'Burundian',
  'Cambodian',
  'Cameroonian',
  'Canadian',
  'Cape Verdean',
  'Central African',
  'Chadian',
  'Chilean',
  'Chinese',
  'Colombian',
  'Comoran',
  'Congolese',
  'Costa Rican',
  'Croatian',
  'Cuban',
  'Cypriot',
  'Czech',
  'Danish',
  'Djibouti',
  'Dominican',
  'Dutch',
  'East Timorese',
  'Ecuadorean',
  'Egyptian',
  'Emirian',
  'Equatorial Guinean',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Fijian',
  'Filipino',
  'Finnish',
  'French',
  'Gabonese',
  'Gambian',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Grenadian',
  'Guatemalan',
  'Guinea-Bissauan',
  'Guinean',
  'Guyanese',
  'Haitian',
  'Herzegovinian',
  'Honduran',
  'Hungarian',
  'I-Kiribati',
  'Icelander',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kazakhstani',
  'Kenyan',
  'Kittian and Nevisian',
  'Kuwaiti',
  'Kyrgyz',
  'Laotian',
  'Latvian',
  'Lebanese',
  'Liberian',
  'Libyan',
  'Liechtensteiner',
  'Lithuanian',
  'Luxembourger',
  'Macedonian',
  'Malagasy',
  'Malawian',
  'Malaysian',
  'Maldivan',
  'Malian',
  'Maltese',
  'Marshallese',
  'Mauritanian',
  'Mauritian',
  'Mexican',
  'Micronesian',
  'Moldovan',
  'Monacan',
  'Mongolian',
  'Moroccan',
  'Mosotho',
  'Motswana',
  'Mozambican',
  'Namibian',
  'Nauruan',
  'Nepalese',
  'New Zealander',
  'Nicaraguan',
  'Nigerian',
  'Nigerien',
  'North Korean',
  'Northern Irish',
  'Norwegian',
  'Omani',
  'Pakistani',
  'Palauan',
  'Panamanian',
  'Papua New Guinean',
  'Paraguayan',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Qatari',
  'Romanian',
  'Russian',
  'Rwandan',
  'Saint Lucian',
  'Salvadoran',
  'Samoan',
  'San Marinese',
  'Sao Tomean',
  'Saudi',
  'Scottish',
  'Senegalese',
  'Serbian',
  'Seychellois',
  'Sierra Leonean',
  'Singaporean',
  'Slovakian',
  'Slovenian',
  'Solomon Islander',
  'Somali',
  'South African',
  'South Korean',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Surinamer',
  'Swazi',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tajik',
  'Tanzanian',
  'Thai',
  'Togolese',
  'Tongan',
  'Trinidadian or Tobagonian',
  'Tunisian',
  'Turkish',
  'Tuvaluan',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Uzbekistani',
  'Venezuelan',
  'Vietnamese',
  'Welsh',
  'Yemenite',
  'Zambian',
  'Zimbabwean'
]

export const countries = [
  { id: 'at', name: 'Austria', name_local: 'Österreich' },
  { id: 'be', name: 'Belgium', name_local: 'België / Belgique / Belgien' },
  { id: 'cz', name: 'Czech Republic', name_local: 'Česká republika' },
  { id: 'fr', name: 'France', name_local: 'France' },
  { id: 'de', name: 'Germany', name_local: 'Deutschland' },
  { id: 'gr', name: 'Greece', name_local: 'Ελλάδα' },
  { id: 'hu', name: 'Hungary', name_local: 'Magyarország' },
  { id: 'it', name: 'Italy', name_local: 'Italia' },
  { id: 'nl', name: 'Netherlands', name_local: 'Nederland' },
  { id: 'pl', name: 'Poland', name_local: 'Polska' },
  { id: 'pt', name: 'Portugal', name_local: 'Portugal' },
  { id: 'es', name: 'Spain', name_local: 'España' },
  { id: 'se', name: 'Sweden', name_local: 'Sverige' },
  { id: 'gb', name: 'United Kingdom', name_local: 'United Kingdom' }
]

export const languages = [
  { id: 'ru', name: 'Russian' },
  { id: 'de', name: 'German' },
  { id: 'fr', name: 'French' },
  { id: 'es', name: 'Spanish' },
  { id: 'it', name: 'Italian' },
  { id: 'tr', name: 'Turkish' },
  { id: 'pl', name: 'Polish' },
  { id: 'uk', name: 'Ukrainian' },
  { id: 'nl', name: 'Dutch' },
  { id: 'ro', name: 'Romanian' },
  { id: 'pt', name: 'Portuguese' },
  { id: 'sv', name: 'Swedish' },
  { id: 'no', name: 'Norwegian' },
  { id: 'da', name: 'Danish' },
  { id: 'fi', name: 'Finnish' },
  { id: 'el', name: 'Greek' },
  { id: 'cs', name: 'Czech' },
  { id: 'hu', name: 'Hungarian' },
  { id: 'sk', name: 'Slovak' },
  { id: 'bg', name: 'Bulgarian' }
]

// Summary
export const craftCategories = [
  'Ceramics and glass crafts',
  'Fibre and textile crafts',
  'Flower crafts',
  'Leatherwork',
  'Houseware',
  'Fashion',
  'Needlework',
  'Paper crafts',
  'Wood and furniture crafts',
  'Stone crafts',
  'Metal crafts',
  'Bone, antler and ivory crafts',
  'Food and agricultural crafts'
]

export const craftTypes = [
  'Traditional',
  'Historical',
  'Archaeological',
  'Educational'
]

// Crafters
export const rolesOptions = [
  'Demostrator',
  'Working normally',
  'Involved in documentation',
  'Sole documenter'
]

export const motivationOptions = [
  'Local or family tradition (peer pressure form previous generations)',
  'Personal interest',
  'To earn (part of) a living',
  'Learning something new',
  'Developing my skillset, a sense of achievement',
  'Being creative',
  'Self-expression',
  'Manual working',
  'Producing (unique) things',
  'Doing something useful',
  'A sense of community',
  'Destressing',
  'Teaching patience',
  'Mental health benefits',
  'Part of a study program/academic course'
]

export const teachingOptions = [
  'They have apprentices',
  'They teach at schools/universities/workshops',
  'Other'
]

export const workingAreaOptionsCrafters = [
  'Rural workshop',
  'Urban workshop',
  'Museum workshop'
]

// Documentation Context
export const documentationOccasionOptions = [
  'As a regular museum demonstration activity for visitors',
  'As part of museum publicity',
  'To produce things needed by the museum (for example - tools, parts of buildings, or items for the shop, or items for museum programs)',
  'As part of a larger program, cf a (funded) project with other partners, like other museums, or universities',
  'To train (candidate) craftspeople',
  'For academic purposes of research or education of students',
  'In the context of a larger event / celebration'
]

// Tools and materials
export const toolsObtainedOptions = [
  'Purchased by trade',
  'Produced or adapted by oneself',
  'Inherited'
]

export const installationsObtainedOptions = [
  'Purchased by trade',
  'Produced or adapted by oneself',
  'Inherited',
  'Unkown'
]

export const materialsObtainedOptions = [
  'From natural environment',
  'Bought from the market / purchased by trade'
]

// Production Process
export const workingAreaOptionsProductionProcess = [
  'Rural workshop',
  'Urban workshop',
  'Museum workshop'
]

// Finished Products
export const reachabilityOptions = [
  'Shops',
  'Markets/Fairs',
  'Direct fromn the workshop',
  'Online shop/website',
  'Other'
]

export const durabilityOptions = [
  'Some years',
  'Ephemeral'
]

export const distributedOptions = [
  'Trade',
  'Informal exchange',
  'Donation/Gifting',
  'Not distributed'
]

export const sourceTypesOptions = [
  'Excavation report',
  'Technical report containing main features/technical drawings for the reconstruction',
  'Historical source',
  'Capture of oral/anecdotal history',
  'Relevant academic literature',
  'Other type of source'
]

export const settlementOptions = [
  'Settlement',
  'Rural/Standalone building',
  'Unknown'
]

export const environmentOptions = [
  'Urban',
  'Village',
  'Household/homestead'
]

export const learningOptions = [
  'From one or more persons (informal)',
  'Apprenticeship (semi formal)',
  'Formal Course (with a diploma)'
]

export const buildingFuncionOptions = [
  'Residential',
  'Non-residential',
  'An annex'
]

export const buildingResidenceOptions = [
  'Seasonal workers house',
  'Farmhouse',
  'Family house',
  'Manor house/castle',
  'Other not listed'
]

export const buildingNonResidentialOptions = [
  'Workshop',
  'Mill',
  'Store',
  'Inn/restaurant/cafe',
  'School',
  'Church/temple',
  'Other not listed'
]

export const buildingAnnexOptions = [
  'Adjoining building',
  'Outbuilding',
  'Barn',
  'Stable',
  'Baking house',
  'Other not listed'
]

export const buildingNewFunctionOptions = [
  'Yes, the building changed to residential',
  'Yes, the building changed to non-residential',
  'Yes, the building changed to an annex',
  'No, the building has not changed use or function'
]

export const buildingNewResidenceOptions = [
  'Farmhouse',
  'Family house',
  'Manor house/castle',
  'Other not listed'
]

export const buildingNewNonResidentialOptions = [
  'Workshop',
  'Mill',
  'Store',
  'Inn/restaurant/cafe',
  'School',
  'Church/temple',
  'Other not listed'
]

export const buildingNewAnnexOptions = [
  'Adjoining building',
  'Outbuilding',
  'Barn',
  'Stable',
  'Baking house',
  'Other not listed'
]

export const buildingObtainedOptions = [
  'Purchased',
  'Donated',
  'Unknown'
]

export const reasonToPresentOptions = [
  'The building is a rare specimen of its type',
  'The building was a piece in a larger important context',
  'The building is a prime example of the following historical characteristics of its time',
  'The building is a prime example of the following architectural characteristics',
  'The building represents a social status or position',
  'The building is important to the national or regional context',
  'The building is of technological interest because'
]

export const buildingEnvironmentOptions = [
  'Stand-alone',
  'Part of a household'
]

export const buildingHouseholdOptions = [
  'Reconstruction of the original household',
  'Household based on several households'
]

export const buildingRealisationOptions = [
  'A rebuild of an original (building up again of the original building, using original substance)',
  'A reconstruction (a new building, based on either historical or archaeological sources but without using original substance)'
]
